apiVersion: apps/v1
kind: Deployment
metadata:
  name: shai-rtp
  namespace: shai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shai-rtp
  template:
    metadata:
      labels:
        app: shai-rtp
    spec:
      imagePullSecrets:
      - name: jfrogcred
      containers:
      - name: shai-rtp
        image: shai01.jfrog.io/shai01-docker/app_trend:2.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CONSUMER_KEY
        - name: CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CONSUMER_SECRET
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ACCESS_TOKEN
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: ACCESS_TOKEN_SECRET
