apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: shai
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJzaGFpMDEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcEJlbVZ5ZEhsMWFTRXgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson