apiVersion: v1
kind: Service
metadata:
  name:  shai-rtp-service
  namespace: shai
spec:
  type: NodePort
  selector:
    app: shai-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000